channels:
  - conda-forge
  - defaults

dependencies:
  - dash
  - dill
  - jsonmerge
  - mat4py
  - nlopt
  - openfast==3.5.2
  - openraft==1.3.1
  - osqp  
  - pcrunch
  - pip
  - pyhams==1.3.0
  #- pyoptsparse
  - rosco==2.9.4
  - smt
  - wisdem==3.16.4
  - pip:
    - dash-bootstrap-components
    - dash-mantine-components
    - dearpygui
    - marmot-agents
# Needs to be done outside of environment file:
#  - m2w64-toolchain # [win]
#  - libpython # [win]
#  - compilers # [not win]
#  - petsc4py # [not win]
#  - mpi4py # [not win]
