general:
    folder_output: output
    fname_output: log_iea22mw_umaine

design_variables:
  control:
    servo:
      pitch_control:
         omega:
           flag: True
           min: 0.025
           max: 0.5
         zeta:
           flag: True
           min: 0.1
           max: 3.0
         Kp_float:
           flag: True
           min: -40
           max: -0 # (v1: 0, v2: -5)
         ptfm_freq:
           flag: True
           min: 0.00001
           max: 1
  floating:
    joints:
      flag: True
      z_coordinate:
          - names: [main_keel, col1_keel, col2_keel, col3_keel]
            lower_bound: -50
            upper_bound: -20
      r_coordinate:
          - names: [col1_keel, col1_freeboard, col2_keel, col2_freeboard, col3_keel, col3_freeboard]
            lower_bound: 35
            upper_bound: 75   
    members:
         flag: True
         groups:
           - names: [column1, column2, column3]
             diameter:
                 lower_bound: 10.0
                 upper_bound: 16.0
                 constant: True

constraints:
  qblade_failed: 
    flag: True 

  floating:
    survival_heel:
      upper_bound: 0.17453292519943295 # 10 deg
    pitch_period:
      flag: True
      upper_bound: 33. # upper bounds are crucial for appropriate constraint definition (default is otherwise set to 1)
      lower_bound: 20.
    heave_period:
      flag: True
      upper_bound: 18.  # upper bounds are crucial for appropriate constraint definition (default is otherwise set to 1)
      lower_bound: 14.
    fixed_ballast_capacity: # Ensures that there is sufficient volume to hold the specified fixed (permanent) ballast",
      flag: True
    variable_ballast_capacity: # Ensures that there is sufficient volume to hold the needed water (variable) ballast to achieve neutral buoyancy
      flag: True
    freeboard_margin:   # keep freeboard from being submerged below water during survival_heel, largest wave
      flag: True
    draft_margin:   # keep draft from raising above water line during survival_heel, largest wave
      flag: True
    fairlead_depth: # keep fairlead above bottom trough of largest wave
      flag: True
  
  control:
    nacelle_acceleration:
      flag: True
      max: 2.7
    rotor_overspeed:
      flag: True
      max: 0.2
    avg_pitch_travel:
      flag: True
      max: 0.085
    #Std_PtfmPitch:
    #  flag: True
    #  max: 2.25
    Max_PtfmPitch:
      flag: True
      max: 7.2
  #user:
  #  - name: aeroelastic_qblade.max_pitch_rate_sim
  #    upper_bound: [0.75]
  #  - name: aeroelastic_qblade.Mean_PtfmPitch
  #    upper_bound: [5]

merit_figure: DEL_TwrBsMyt    # Merit figure of the optimization problem. The options are 'AEP' - 'LCOE' - 'Cp' - 'blade_mass' - 'blade_tip_deflection'
  
driver:
  optimization:
    flag: True
    tol: 1.e-3              # Optimality tolerance
    max_iter: 150           # Maximum number of iterations (SLSQP)
    solver: LN_COBYLA         # Optimization solver. Other options are 'SLSQP' - 'CONMIN'
    
recorder:
    flag: True                          # Flag to activate OpenMDAO recorder
    file_name: log_iea22mw_umaine.sql # log_iea22mw_umaine.sql   # Name of OpenMDAO recorder
    includes: [
      'floatingse.system_structural_mass',
      'floatingse.platform_mass', 
      'floatingse.pitch_period', 
      'floatingse.heave_period', 
      'floatingse.fixed_ballast_capacity', 
      'floatingse.variable_ballast_capacity', 
      'floatingse.mooring_heel', 
      'floatingse.freeboard_margin', 
      'floatingse.draft_margin', 
      'floatingse.fairlead_depth', 
      'aeroelastic_qblade.DEL_TwrBsMyt', 
      'aeroelastic_qblade.DEL_RootMyb'
    ]

