general:
    folder_output: outputs/1p6_verification
    fname_output: refturb_output

design_variables:
  control:
    servo:
      pitch_control:
          omega:
            flag: True
            min: 0.025
            max: 0.5
          zeta:
            flag: True
            min: 0.1
            max: 3.0
          Kp_float:
            flag: True
            min: -40
            max: 0
          ptfm_freq:
            flag: True
            max: 1
    
merit_figure: DEL_TwrBsMyt  # Merit figure of the optimization problem. The options are 'AEP' - 'LCOE' - 'Cp' - 'blade_mass' - 'blade_tip_deflection'

constraints:
  control:
    rotor_overspeed:
      flag: True
      min: 0.0
      max: 0.2
    Max_PtfmPitch:
      flag: True
      max: 6
    Std_PtfmPitch:
      flag: False
      max: 2.

driver:
  optimization:
    flag: True
    tol: 2.e-3              # Optimality tolerance
    max_iter: 200           
    solver: LN_COBYLA       
    
    
recorder:
    flag: True              # Flag to activate OpenMDAO recorder
    file_name: log_opt.sql  # Name of OpenMDAO recorder
    includes: ['floatingse.platform_mass']
